title: 'coreBOS Documentation'
default_lang: en
author:
  name: 'Joe Bordes'
  email: joe@corebos.org
taxonomies:
  - category
  - tag
metadata:
  description: 'coreBOS Documentation Site. Proud member of the coreBOS family! Visit our Website and the Forum.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
