enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo:
  user/themes/quark/images/logo/corebos_logo.png:
    name: corebos_logo.png
    type: image/png
    size: 8048
    path: user/themes/quark/images/logo/corebos_logo.png
custom_logo_mobile:
  user/themes/quark/images/logo/corebos_logo.png:
    name: corebos_logo.png
    type: image/png
    size: 8048
    path: user/themes/quark/images/logo/corebos_logo.png
